// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAemPEOI27Ktee4Z_VDlddjxaDeLCE0KMM',
    appId: '1:200852093381:web:b17952374515cda17f73ac',
    messagingSenderId: '200852093381',
    projectId: 'eventooweb',
    authDomain: 'eventooweb.firebaseapp.com',
    storageBucket: 'eventooweb.firebasestorage.app',
    measurementId: 'G-K6L9R8218F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgDp2_uc3YIBccELyipkNlyzHki6dsqps',
    appId: '1:200852093381:android:13fa63da49db9d727f73ac',
    messagingSenderId: '200852093381',
    projectId: 'eventooweb',
    storageBucket: 'eventooweb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIR4utDqbtaNkJeTALH3k6eatMsBE3HjU',
    appId: '1:200852093381:ios:c5df7515786a80177f73ac',
    messagingSenderId: '200852093381',
    projectId: 'eventooweb',
    storageBucket: 'eventooweb.firebasestorage.app',
    androidClientId: '200852093381-hqmr5bg3smlm6ubiirqeo90lpjivsfp0.apps.googleusercontent.com',
    iosClientId: '200852093381-7aljv8gndmuubv7mppr3l5hleimt3cg4.apps.googleusercontent.com',
    iosBundleId: 'io.eventoo.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIR4utDqbtaNkJeTALH3k6eatMsBE3HjU',
    appId: '1:200852093381:ios:c5df7515786a80177f73ac',
    messagingSenderId: '200852093381',
    projectId: 'eventooweb',
    storageBucket: 'eventooweb.firebasestorage.app',
    androidClientId: '200852093381-hqmr5bg3smlm6ubiirqeo90lpjivsfp0.apps.googleusercontent.com',
    iosClientId: '200852093381-7aljv8gndmuubv7mppr3l5hleimt3cg4.apps.googleusercontent.com',
    iosBundleId: 'io.eventoo.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0hlVNaTs4rmBTl91B78FaLz6eRqBxVnM',
    appId: '1:200852093381:web:1df5423d32d82f4e7f73ac',
    messagingSenderId: '200852093381',
    projectId: 'eventooweb',
    authDomain: 'eventooweb.firebaseapp.com',
    storageBucket: 'eventooweb.firebasestorage.app',
    measurementId: 'G-8YJQ2SWZE5',
  );
}