# Set the platform to 15.5 for mobile_scanner
platform :ios, '15.5'

# 1. Dynamically find the Flutter Root path
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
end

# 2. Load the Flutter podhelper script
# This provides the 'flutter_install_all_ios_pods' method
load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # 3. This now exists because we 'load'ed the podhelper above
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Force every dependency to 15.5 to avoid conflicts
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    end
  end
end