platform :ios, '15.5'

# These lines allow the Podfile to talk to the Flutter SDK
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    # This is fine on Windows; Codemagic will generate this file during the build
    return "" 
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
end

# Load the helper scripts from the Flutter SDK
flutter_bin_path = File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')
require flutter_bin_path if File.exist?(flutter_bin_path)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # This is the magic command that links firebase_analytics and others
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    end
  end
end